In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

In [2]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp310-cp310-macosx_11_0_universal2.whl.metadata (1.4 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from catboost) (3.10.9)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from catboost) (2.2.6)
Requirement already satisfied: pandas<4.0,>=0.24 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from catboost) (1.15.3)
Collecting plotly (from catboost)
  Downloading plotly-6.8.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: six in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from matplotlib->catboost) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from matplotlib->catboost) (3.3.2)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Downloading narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Downloading catboost-1.2.10-cp310-cp310-macosx_11_0_universal2.whl (28.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.8/28.8 MB 2.3 MB/s  0:00:12m0:00:0100:01
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Downloading plotly-6.8.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 13.2 MB/s  0:00:00 eta 0:00:01
Downloading narwhals-2.23.0-py3-none-any.whl (458 kB)
Installing collected packages: narwhals, graphviz, plotly, catboost
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [catboost]3/4 [catboost]
Successfully installed catboost-1.2.10 graphviz-0.21 narwhals-2.23.0 plotly-6.8.0

In [6]:
!pip uninstall xgboost -y
!pip install xgboost

Found existing installation: xgboost 3.2.0
Uninstalling xgboost-3.2.0:
  Successfully uninstalled xgboost-3.2.0
Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in /Users/arghyachakraborty/Desktop/ml_project/myenv/lib/python3.10/site-packages (from xgboost) (1.15.3)
Using cached xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl (2.3 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [8]:
df = pd.read_csv('data/stud.csv')

In [9]:
df.head()

   gender race_ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [10]:
# Preparing X and Y
X = df.drop(columns=['math_score'], axis=1)

In [11]:
X.head()

   gender race_ethnicity  ... reading_score writing_score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 7 columns]

In [12]:
y = df['math_score']

In [13]:
# Create Column transformer with 3 types of transformers
num_features = X.select_dtypes(exclude=['object']).columns
cat_features = X.select_dtypes(include=['object']).columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features),
    ]
)

In [14]:
X = preprocessor.fit_transform(X)

In [16]:
X.shape

(1000, 19)

In [17]:
# separete train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)